---
- name: Clone a dotfiles github repository
  git:
    repo: git@github.com:kzy52/dotfiles.git
    dest: ~/workspace/dotfiles
    clone: yes
    update: yes

- name: Run Shell
  shell: sh ./install.sh
  args:
    chdir: ~/workspace/dotfiles

- name: Create tmuxinator symlink
  file: src=~/Dropbox/dotfiles/.tmuxinator dest=~/.tmuxinator state=link force=yes

- name: Create .gitconfig.local symlink
  file: src=~/Dropbox/dotfiles/.gitconfig.local dest=~/.gitconfig.local state=link force=yes
